spring:
  datasource:
    url: jdbc:${DB_BASE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5450}/${DB_NAME:Nails.A_db}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

server:
  port: ${SERVER_PORT:8080}
